import type { Session } from '@supabase/supabase-js';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { supabase } from '@/lib/supabase';

type Tx = { id: string; description: string; amount: number; occurred_on: string; due_on: string | null; status: 'confirmed' | 'review' | 'ignored'; raw_data: { category?: string } | null };
type Account = { id: string; name: string; opening_balance: number };
type Budget = { id: string; category: string; amount: number };
type Tab = 'inicio' | 'lancamentos' | 'revisao' | 'orcamentos';
const green = '#197a55';
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });

function parseEntry(text: string) {
  const match = text.match(/(?:r\$\s*)?(\d{1,9}(?:[.,]\d{1,2})?)/i);
  if (!match) return null;
  const value = Number(match[1].replace(',', '.'));
  if (!Number.isFinite(value) || value <= 0) return null;
  const income = /\b(recebi|ganhei|sal[aá]rio|receita|entrada|vendi)\b/i.test(text);
  const lower = text.toLowerCase();
  const category = income ? 'Receita' : /mercado|comida|almo[cç]o|jantar|restaurante/.test(lower) ? 'Alimentação' : /aluguel|condom[ií]nio|luz|energia|[aá]gua|internet/.test(lower) ? 'Moradia' : /uber|gasolina|combust[ií]vel|ônibus|onibus/.test(lower) ? 'Transporte' : /farm[aá]cia|m[eé]dico|consulta|sa[uú]de/.test(lower) ? 'Saúde' : /cinema|show|bar|viagem|lazer/.test(lower) ? 'Lazer' : 'Outros';
  const dueMatch = text.match(/\b(?:vencimento|vence|venc\.?|dia)\s*(?:em|no|:|-)?\s*(\d{1,2})\/(\d{1,2})(?:\/(\d{2,4}))?\b/i);
  let dueOn: string | null = null;
  if (dueMatch) { const now = new Date(); const day = Number(dueMatch[1]); const month = Number(dueMatch[2]); let year = dueMatch[3] ? Number(dueMatch[3]) : now.getFullYear(); if (year < 100) year += 2000; const date = new Date(year, month - 1, day, 12); if (date.getMonth() === month - 1 && date.getDate() === day) { if (!dueMatch[3] && date < now) date.setFullYear(year + 1); dueOn = date.toISOString().slice(0, 10); } }
  const description = text.replace(match[0], '').replace(/[-–—]?\s*\b(?:vencimento|vence|venc\.?|dia)\s*(?:em|no|:|-)?\s*\d{1,2}\/\d{1,2}(?:\/\d{2,4})?\b/gi, ' ').replace(/\b(gastei|paguei|comprei|recebi|ganhei|sal[aá]rio|receita|entrada|vendi)\b/gi, '').replace(/\b(com|de|em|no|na)\b/gi, ' ').replace(/\s+/g, ' ').trim();
  return { amount: income ? value : -value, description: description || (income ? 'Receita' : 'Despesa'), category, dueOn };
}

function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false);
  async function enter() { if (!email.trim() || !password) return Alert.alert('Preencha o e-mail e a senha.'); setLoading(true); const { error } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); setLoading(false); if (error) Alert.alert('Não foi possível entrar', error.message); }
  return <SafeAreaView style={s.auth}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={s.authInner}>
    <View style={s.logo}><Text style={s.logoText}>S</Text></View><Text style={s.authTitle}>Saldo Aí</Text><Text style={s.subtitle}>Sua vida financeira em um só lugar.</Text>
    <View style={s.card}><Text style={s.label}>E-mail</Text><TextInput style={s.input} autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="voce@email.com" /><Text style={s.label}>Senha</Text><TextInput style={s.input} secureTextEntry value={password} onChangeText={setPassword} placeholder="Sua senha" /><Pressable style={s.primary} onPress={enter} disabled={loading}><Text style={s.primaryText}>{loading ? 'Entrando...' : 'Entrar'}</Text></Pressable><Text style={s.help}>Use o mesmo login do site.</Text></View>
  </KeyboardAvoidingView></SafeAreaView>;
}

function Main({ session }: { session: Session }) {
  const [tab, setTab] = useState<Tab>('inicio'); const [txs, setTxs] = useState<Tx[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [refreshing, setRefreshing] = useState(false); const [text, setText] = useState(''); const [saving, setSaving] = useState(false);
  const month = new Date().toISOString().slice(0, 7);
  const load = useCallback(async () => {
    setRefreshing(true); const [tx, ac, bu] = await Promise.all([supabase.from('transactions').select('id,description,amount,occurred_on,due_on,status,raw_data').neq('status', 'ignored').order('occurred_on', { ascending: false }).limit(100), supabase.from('accounts').select('id,name,opening_balance').order('created_at'), supabase.from('budgets').select('id,category,amount').eq('month', `${month}-01`).order('category')]); setRefreshing(false);
    const error = tx.error || ac.error || bu.error; if (error) return Alert.alert('Erro ao atualizar', error.message);
    setTxs((tx.data || []).map((x) => ({ ...x, amount: Number(x.amount) })) as Tx[]); setAccounts((ac.data || []).map((x) => ({ ...x, opening_balance: Number(x.opening_balance) }))); setBudgets((bu.data || []).map((x) => ({ ...x, amount: Number(x.amount) })));
  }, [month]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const confirmed = txs.filter((x) => x.status === 'confirmed'); const review = txs.filter((x) => x.status === 'review'); const current = confirmed.filter((x) => x.occurred_on.startsWith(month));
  const income = current.filter((x) => x.amount > 0).reduce((a, x) => a + x.amount, 0); const expense = Math.abs(current.filter((x) => x.amount < 0).reduce((a, x) => a + x.amount, 0)); const balance = accounts.reduce((a, x) => a + x.opening_balance, 0) + confirmed.reduce((a, x) => a + x.amount, 0);
  async function add() { const parsed = parseEntry(text); if (!parsed) return Alert.alert('Não encontrei o valor', 'Tente: “gastei 50 no mercado”.'); setSaving(true); const { error } = await supabase.from('transactions').insert({ user_id: session.user.id, description: parsed.description, amount: parsed.amount, occurred_on: new Date().toISOString().slice(0, 10), due_on: parsed.dueOn, status: 'confirmed', raw_data: { category: parsed.category, source: 'mobile-assistant', original_text: text } }); setSaving(false); if (error) return Alert.alert('Não foi possível lançar', error.message); setText(''); await load(); Alert.alert('Pronto!', `${parsed.description}: ${money.format(parsed.amount)}${parsed.dueOn ? `\nVence em ${new Date(`${parsed.dueOn}T12:00:00`).toLocaleDateString('pt-BR')}` : ''}`); }
  async function decide(id: string, status: 'confirmed' | 'ignored') { const { error } = await supabase.from('transactions').update({ status }).eq('id', id); if (error) Alert.alert('Erro', error.message); else await load(); }
  const title = tab === 'inicio' ? 'Visão geral' : tab === 'lancamentos' ? 'Lançamentos' : tab === 'revisao' ? 'Revisão' : 'Orçamentos'; const shown = tab === 'revisao' ? review : confirmed;
  return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={load} tintColor={green} />}>
    <View style={s.header}><View><Text style={s.eyebrow}>SALDO AÍ</Text><Text style={s.title}>{title}</Text></View><Pressable onPress={() => supabase.auth.signOut()}><Text style={s.exit}>Sair</Text></Pressable></View>
    {tab === 'inicio' && <><View style={s.balance}><Text style={s.balanceLabel}>Saldo atual</Text><Text style={s.balanceValue}>{money.format(balance)}</Text><Text style={s.balanceHint}>{accounts.length} conta(s) nos seus dados</Text></View><View style={s.metrics}><Metric label="Receitas do mês" value={income} positive /><Metric label="Despesas do mês" value={expense} /></View><View style={s.card}><Text style={s.cardTitle}>✦ Lançamento inteligente</Text><Text style={s.muted}>Escreva naturalmente. O Saldo Aí identifica o valor e a categoria.</Text><TextInput style={[s.input, s.smart]} value={text} onChangeText={setText} placeholder="Ex.: gastei 50 no mercado" multiline /><Pressable style={s.primary} onPress={add} disabled={saving}><Text style={s.primaryText}>{saving ? 'Salvando...' : 'Lançar agora'}</Text></Pressable></View><View style={s.card}><Text style={s.cardTitle}>Últimos lançamentos</Text>{confirmed.slice(0, 5).map((x) => <TxRow key={x.id} item={x} />)}{!confirmed.length && <Empty text="Nenhum lançamento confirmado." />}</View></>}
    {(tab === 'lancamentos' || tab === 'revisao') && <View style={s.card}><Text style={s.cardTitle}>{tab === 'revisao' ? `${review.length} aguardando confirmação` : `${confirmed.length} lançamentos`}</Text>{shown.map((x) => <View key={x.id}><TxRow item={x} />{tab === 'revisao' && <View style={s.actions}><Pressable style={s.secondary} onPress={() => decide(x.id, 'ignored')}><Text>Ignorar</Text></Pressable><Pressable style={s.approve} onPress={() => decide(x.id, 'confirmed')}><Text style={s.primaryText}>Aprovar</Text></Pressable></View>}</View>)}{!shown.length && <Empty text={tab === 'revisao' ? 'Nada aguardando revisão.' : 'Nenhum lançamento ainda.'} />}</View>}
    {tab === 'orcamentos' && <View style={s.card}><Text style={s.cardTitle}>Planejamento do mês</Text>{budgets.map((b) => { const spent = current.filter((x) => x.amount < 0 && (x.raw_data?.category || 'Outros') === b.category).reduce((a, x) => a + Math.abs(x.amount), 0); const pct = Math.min(100, Math.round(spent / b.amount * 100)); return <View key={b.id} style={s.budget}><View style={s.budgetHead}><Text style={s.txName}>{b.category}</Text><Text style={s.muted}>{money.format(spent)} de {money.format(b.amount)}</Text></View><View style={s.track}><View style={[s.fill, { width: `${pct}%`, backgroundColor: pct >= 100 ? '#bd4d4d' : pct >= 80 ? '#d39a2f' : green }]} /></View></View>; })}{!budgets.length && <Empty text="Seus orçamentos definidos no site aparecerão aqui." />}</View>}
  </ScrollView><View style={s.nav}><Nav label="Início" icon="⌂" active={tab === 'inicio'} onPress={() => setTab('inicio')} /><Nav label="Lançamentos" icon="⇅" active={tab === 'lancamentos'} onPress={() => setTab('lancamentos')} /><Nav label="Revisão" icon="✓" badge={review.length} active={tab === 'revisao'} onPress={() => setTab('revisao')} /><Nav label="Orçamentos" icon="◎" active={tab === 'orcamentos'} onPress={() => setTab('orcamentos')} /></View></SafeAreaView>;
}

function Metric({ label, value, positive }: { label: string; value: number; positive?: boolean }) { return <View style={s.metric}><Text style={s.muted}>{label}</Text><Text style={[s.metricValue, positive ? s.green : s.red]}>{money.format(value)}</Text></View>; }
function Empty({ text }: { text: string }) { return <Text style={s.empty}>{text}</Text>; }
function TxRow({ item }: { item: Tx }) { return <View style={s.tx}><View style={[s.txIcon, item.amount > 0 && s.txIconGreen]}><Text style={item.amount > 0 ? s.green : s.red}>{item.amount > 0 ? '↗' : '↘'}</Text></View><View style={s.txInfo}><Text style={s.txName} numberOfLines={1}>{item.description}</Text><Text style={s.muted}>{item.raw_data?.category || 'Outros'} · {item.due_on ? `vence ${new Date(`${item.due_on}T12:00:00`).toLocaleDateString('pt-BR')}` : new Date(`${item.occurred_on}T12:00:00`).toLocaleDateString('pt-BR')}</Text></View><Text style={[s.txValue, item.amount > 0 ? s.green : s.red]}>{item.amount > 0 ? '+' : '-'} {money.format(Math.abs(item.amount))}</Text></View>; }
function Nav({ label, icon, active, badge, onPress }: { label: string; icon: string; active: boolean; badge?: number; onPress: () => void }) { return <Pressable style={s.navItem} onPress={onPress}><View><Text style={[s.navIcon, active && s.green]}>{icon}</Text>{!!badge && <Text style={s.badge}>{badge}</Text>}</View><Text style={[s.navLabel, active && s.green]}>{label}</Text></Pressable>; }
export default function Index() { const [session, setSession] = useState<Session | null | undefined>(); useEffect(() => { supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data } = supabase.auth.onAuthStateChange((_e, next) => setSession(next)); return () => data.subscription.unsubscribe(); }, []); if (session === undefined) return <SafeAreaView style={s.loading}><ActivityIndicator color={green} size="large" /></SafeAreaView>; return session ? <Main session={session} /> : <Login />; }

const serif = Platform.OS === 'ios' ? 'Georgia' : 'serif';
const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#f5f7f3' }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center' }, content: { padding: 20, paddingBottom: 108, gap: 14 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: green, fontSize: 11, fontWeight: '800', letterSpacing: 1.8 }, title: { color: '#17231c', fontFamily: serif, fontSize: 30, fontWeight: '700', marginTop: 5 }, exit: { color: '#718078', fontWeight: '700' }, balance: { backgroundColor: green, borderRadius: 22, padding: 24, minHeight: 150, justifyContent: 'center', elevation: 5 }, balanceLabel: { color: '#dceee5', fontSize: 13 }, balanceValue: { color: 'white', fontFamily: serif, fontSize: 34, fontWeight: '700', marginVertical: 12 }, balanceHint: { color: '#b9d7c8', fontSize: 11 }, metrics: { flexDirection: 'row', gap: 12 }, metric: { flex: 1, backgroundColor: 'white', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#e3e9e5' }, metricValue: { fontSize: 17, fontWeight: '800', marginTop: 10 }, green: { color: green }, red: { color: '#bd4d4d' },
  card: { backgroundColor: 'white', borderRadius: 18, padding: 18, borderWidth: 1, borderColor: '#e3e9e5' }, cardTitle: { fontSize: 17, fontWeight: '800', color: '#1b2820', marginBottom: 7 }, muted: { color: '#748179', fontSize: 11, lineHeight: 16 }, input: { borderWidth: 1, borderColor: '#d9e2dc', borderRadius: 12, backgroundColor: '#fff', paddingHorizontal: 14, minHeight: 48, color: '#17231c', fontSize: 15 }, smart: { marginTop: 16, paddingTop: 13, minHeight: 68, textAlignVertical: 'top' }, label: { color: '#45534b', fontWeight: '700', fontSize: 12, marginBottom: 7, marginTop: 14 }, primary: { backgroundColor: green, borderRadius: 12, minHeight: 49, alignItems: 'center', justifyContent: 'center', marginTop: 12 }, primaryText: { color: 'white', fontWeight: '800' }, tx: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderTopWidth: 1, borderTopColor: '#edf0ee' }, txIcon: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fbeeee' }, txIconGreen: { backgroundColor: '#eaf5ef' }, txInfo: { flex: 1, marginHorizontal: 11 }, txName: { color: '#202b25', fontWeight: '700', fontSize: 13 }, txValue: { fontWeight: '800', fontSize: 12 }, actions: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end', paddingBottom: 10 }, secondary: { borderWidth: 1, borderColor: '#d9e2dc', borderRadius: 9, paddingHorizontal: 15, paddingVertical: 9 }, approve: { backgroundColor: green, borderRadius: 9, paddingHorizontal: 15, paddingVertical: 10 }, empty: { color: '#849088', textAlign: 'center', paddingVertical: 28 }, budget: { marginTop: 18 }, budgetHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, track: { height: 8, backgroundColor: '#edf1ee', borderRadius: 10, overflow: 'hidden', marginTop: 9 }, fill: { height: 8, borderRadius: 10 },
  nav: { position: 'absolute', left: 10, right: 10, bottom: 10, minHeight: 70, borderRadius: 20, flexDirection: 'row', backgroundColor: '#fff', borderWidth: 1, borderColor: '#e1e7e3', elevation: 8 }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' }, navIcon: { textAlign: 'center', color: '#7c8981', fontSize: 21 }, navLabel: { color: '#7c8981', fontSize: 9, fontWeight: '700', marginTop: 3 }, badge: { position: 'absolute', right: -11, top: -4, backgroundColor: '#c55353', color: 'white', minWidth: 17, height: 17, borderRadius: 9, textAlign: 'center', fontSize: 10, lineHeight: 17, fontWeight: '800' }, auth: { flex: 1, backgroundColor: '#eff6f1' }, authInner: { flex: 1, justifyContent: 'center', padding: 25 }, logo: { width: 54, height: 54, borderRadius: 17, backgroundColor: green, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' }, logoText: { color: '#fff', fontFamily: serif, fontSize: 32, fontStyle: 'italic', fontWeight: '800' }, authTitle: { textAlign: 'center', color: '#17231c', fontFamily: serif, fontSize: 34, fontWeight: '700', marginTop: 15 }, subtitle: { textAlign: 'center', color: '#748179', marginTop: 7, marginBottom: 25 }, help: { textAlign: 'center', color: '#819087', fontSize: 11, marginTop: 16 },
});
